title: RemVos
email:
description: > # this means to ignore newlines until "baseurl:"
  Too many hobby projects...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://remvos.github.io" # the base hostname & protocol for your site
twitter_username: remvos
github_username:  remvos
google_analytics: UA-83975382-1

# Build settings
markdown: kramdown
theme: minima
